### PR TITLE
chore(ci): add GitHub Actions, close #79

### LINKED ISSUE #79: Setup Continuous Integration
**Is your feature request related to a problem? Please describe.**
I am bit suprised I don't see any Continuous Integration (CI) on a matured-project like this.

By using CI, we could automatically:
- lint yaml files, with `bin/console lint:yaml config`  
- lint Twig files, with `bin/console lint:twig templates`
- lint Symfony container, with `bin/console lint:container`
- run a static analysis tools for PHP, like [PHPStan](https://phpstan.org/) or [Psalm](https://psalm.dev/)
- run tests for PHP, like [PHPUnit](https://phpunit.de/), [phpspec](http://www.phpspec.net/en/stable/), or [Behat](https://docs.behat.org/en/latest/)...
- lint the JS files, with [ESLint](https://eslint.org/)
- lint the CSS files with [Stylelint](https://stylelint.io/)
- run tests for JS, with [Jest](https://jestjs.io/) or another tool
- run [Webpack Encore](https://github.com/symfony/webpack-encore) to see if the JS/CSS assets are _buildable_

If we run the CI for each pull request, we can prevent any regression to be shipped in production.

**Describe the solution you'd like**
Use [GitHub Actions](https://github.com/features/actions). I've used for many months and I'm really happy about it.

**Describe alternatives you've considered**
Use [Travis](https://travis-ci.org/) but it's slow, or [CircleCI](https://circleci.com/) but it's not free.

**Additional context**
Nope.

### PR DESCRIPTION
**Pull request by Kocal**
Checks are not showing up yet surely because of _security_ reason (maybe because I'm not an owner, the worklow will only run when this PR will be merged? :thinking:), but see https://github.com/Kocal/GameHer/pull/1 to see it in action: 
Capture d’écran de 2020-09-12 21-43-36

It feels a bit empty and useless for now, but PHPStan, PHP CS Fixer, ESLint and more are just waiting to be added! :eyes: 

WDYT @Noelierx?

### CODE REVIEW

**Review by chypriote — APPROVED** [review]

**Comment by Noelierx** [comment]
Can I merge it? @Kocal @chypriote

**Comment by Kocal** [comment]
Yeah if you want

**Comment by Noelierx** [comment]
@Kocal Pour info, ça fonctionne au top ! 💪
Merci à toi 😄

**Comment by Kocal** [comment]
@Noelierx parfait alors ! :)

**Pull request merged**
