### PR TITLE
Fixed margin in Navigation menu for mobile users

### PR DESCRIPTION
**Pull request by dastgirp**
Fixes #8

Screenshot:
image

### CODE REVIEW

**Comment by m1ga** [comment]
please check on different resolutions eg. iPad:
Screenshot_20191008_184335
first menu item is cut off

**Comment by Noelierx** [comment]
@dastgirp see @m1ga comment about responsive on other resolution 
But thanks a lot for the try !

**Comment by dastgirp** [comment]
@Noelierx Fixed.

**Comment by m1ga** [comment]
@dastgirp this one looks a bit better 
```css
	margin-top: 5rem;
	@media (max-width: 600px) {
		margin-top: 4rem;
	}
```

**Pull request merged**
